# Generated by Django 5.1.4 on 2025-06-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Rating",
                "verbose_name_plural": "Ratings",
            },
        ),
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 star"),
                    (2, "2 stars"),
                    (3, "3 stars"),
                    (4, "4 stars"),
                    (5, "5 stars"),
                ],
                default=1,
            ),
        ),
    ]
