# Generated by Django 5.1.4 on 2025-03-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_item', '0001_initial'),
        ('tag', '0002_alter_tag_description_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='resources', to='tag.tag'),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
