# Generated by Django 5.1.4 on 2025-06-08 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_alter_category_name"),
        ("resource_item", "0003_alter_resourceitem_user"),
        ("tag", "0002_alter_tag_description_alter_tag_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. The main topic/category for this resource.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_items",
                to="category.category",
            ),
        ),
        migrations.AlterField(
            model_name="resourceitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this resource was created.",
            ),
        ),
        migrations.AlterField(
            model_name="resourceitem",
            name="description",
            field=models.TextField(
                help_text="A short description of the resource (max 500 characters).",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="resourceitem",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional. One or more tags for this resource.",
                related_name="resources",
                to="tag.tag",
            ),
        ),
        migrations.AlterField(
            model_name="resourceitem",
            name="title",
            field=models.CharField(
                help_text="The title of the resource (max 200 characters).",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="resourceitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this resource was last updated.",
            ),
        ),
        migrations.AlterField(
            model_name="resourceitem",
            name="url",
            field=models.URLField(
                help_text="A unique URL pointing to the resource.", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="resourceitem",
            name="user",
            field=models.ForeignKey(
                help_text="The user who uploaded this resource.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
