# Generated by Django 5.1.4 on 2025-06-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_item", "0004_alter_resourceitem_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceitem",
            name="average_rating",
            field=models.FloatField(
                default=0.0,
                help_text="Average rating of this resource, calculated from user ratings.",
            ),
        ),
        migrations.AddField(
            model_name="resourceitem",
            name="rating_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of ratings this resource has received."
            ),
        ),
    ]
